name: Video Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Install dependent
        run: |
          sudo apt update
          sudo apt install  ffmpeg -y
          sudo pip3 install requests bs4 lxml
      
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Fetch video info
        run: |
          python3 film_info.py

      - name: Download video
        run: |
          aria2c --seed-time=0 $(cat url.txt)
      
      - name: Slice video
        run: |
          ffmpeg -i $(cat name.txt)/$(cat name.txt).mp4 -c copy -f hls -bsf:v h264_mp4toannexb -hls_time 10 -hls_list_size 0 -hls_segment_filename hls%4d.ts index.m3u8

      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.VIDEO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github@chan.im"
          git config --global user.name "ghcdn"
      
      - name: Create Github repo
        env:
          PUSH_TOKEN: ${{ secrets.REPO_KEY }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token $PUSH_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user/repos \
          -d "{\"name\": \"$(cat name.txt)\"}"
      
      - name: Push to Github
        run: |
          mkdir -p gitdir/res/
          mv index.m3u8 gitdir/res/
          mv hls*.ts gitdir/res/
          mv *.jpg gitdir/
          mv README.md gitdir/
          cd gitdir
          git init
          git add res/hls00??.ts
          git add res/index.m3u8
          git add *.jpg README.md
          git commit -m "first commit"
          git remote add origin git@github.com:ghcdn/$(cat ../name.txt).git
          git push -u origin master
          for i in {1..9};do
            git add res/hls0$i??.ts
            git commit -m "$i st commit"
            git push
          done
