name: Video Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Install dependent
        run: |
          sudo apt update
          sudo apt install  ffmpeg -y
          sudo pip3 install requests bs4 lxml
      
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Fetch video info
        run: |
          python3 setup.py

      - name: Download video
        run: |
          aria2c --conf-path=./aria2.conf $(cat url.txt)
      
      - name: Process video
        run: |
          ffmpeg -ss 3 -i $(cat name.txt)/$(cat name.txt).mp4 -vf "select=gt(scene\,0.4)" -frames:v 16 -vsync vfr -vf fps=fps=1/450 thumb%02d.jpg
          ffmpeg -i $(cat name.txt)/$(cat name.txt).mp4 -c copy -f hls -bsf:v h264_mp4toannexb -hls_list_size 0 -hls_segment_filename hls%4d.ts index.m3u8
          rm -rf $(cat name.txt)

      - name: Setup Git
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.VIDEO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github@chan.im"
          git config --global user.name "ghcdn"
      
      - name: Create Github repo
        env:
          PUSH_TOKEN: ${{ secrets.REPO_KEY }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token $PUSH_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user/repos \
          -d "{\"name\": \"$(cat name.txt)\"}"
      
      - name: Push to Github
        run: |
          mkdir -p gitdir/res/
          mkdir -p gitdir/img/
          mv README.md index.html gitdir/
          mv *.jpg gitdir/img  
          mv index.m3u8 hls*.ts gitdir/res/
          cd gitdir
          git init
          git add img README.md index.html res/index.m3u8
          git commit -m "add film info"
          git remote add origin git@github.com:ghcdn/$(cat ../name.txt).git
          git push -u origin master
          for i in {0..9};do
            for j in {0..9};do
              files=(res/hls$i$j??.ts)
              if [ -f ${files[0]} ];then
                git add "${files[@]}"
                git commit -m "$i st commit"
                git push
              else
                exit 0
              fi
            done
          done
